# Generated by Django 3.0.3 on 2021-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countryCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('confirmed', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('updated', models.CharField(max_length=100)),
            ],
        ),
    ]
